local M = {}

local enry_lang_to_exts = {
    -- Taken from go-enry's extensions.go file
    ["Ada"] = { ".adb", ".ada", ".ads" },
    ["Agda"] = { ".agda" },
    ["Apex"] = { ".cls", ".trigger" },
    ["Assembly"] = { ".asm", ".a51", ".i", ".inc" }, -- .nas and .nasm filetypes moved for their own type. Enry will still autoidentify nasm snippets as Assembly
    ["Astro"] = { ".astro" },
    ["BibTeX"] = { ".bib", ".bibtex" },
    ["Bicep"] = { ".bicep", ".bicepparam" },
    ["BitBake"] = { ".bb", ".bbappend", ".bbclass", ".inc" },
    ["C"] = { ".c", ".cats", ".h", ".idc" },
    ["C#"] = { ".cs", ".cake", ".cs.pp", ".csx", ".linq" },
    ["Cairo"] = { ".cairo" },
    ["Cap'n Proto"] = { ".capnp" },
    ["Clojure"] = { ".clj", ".bb", ".boot", ".cl2", ".cljc", ".cljs", ".cljs.hl", ".cljscm", ".cljx", ".hic" },
    ["CMake"] = { ".cmake", ".cmake.in" },
    ["Common Lisp"] = { ".lisp", ".asd", ".cl", ".l", ".lsp", ".ny", ".podsl", ".sexp" },
    ["C++"] = {
        ".cpp",
        ".c++",
        ".cc",
        ".cp",
        ".cppm",
        ".cxx",
        ".h",
        ".h++",
        ".hh",
        ".hpp",
        ".hxx",
        ".inc",
        ".inl",
        ".ino",
        ".ipp",
        ".ixx",
        ".re",
        ".tcc",
        ".tpp",
        ".txx",
    },
    ["CSS"] = { ".css" },
    ["CSV"] = { ".csv" },
    ["Cuda"] = { ".cu", ".cuh" },
    ["CUE"] = { ".cue" },
    ["D"] = { ".d", ".di" },
    ["Dart"] = { ".dart" },
    ["Dhall"] = { ".dhall" },
    ["Diff"] = { ".diff", ".patch" },
    ["Dockerfile"] = { ".dockerfile" },
    ["EBNF"] = { ".ebnf" },
    ["Elixir"] = { ".ex", ".exs" },
    ["Elm"] = { ".elm" },
    ["Elvish"] = { ".elv" },
    ["Erlang"] = { ".erl", ".app", ".app.src", ".es", ".escript", ".hrl", ".xrl", ".yrl" },
    ["Faust"] = { ".dsp" },
    ["Fennel"] = { ".fnl" },
    ["fish"] = { ".fish" },
    ["Forth"] = { ".fth", ".4th", ".f", ".for", ".forth", ".fr", ".frt", ".fs" },
    ["Fortran"] = { ".f", ".f77", ".for", ".fpp" },
    ["GDScript"] = { ".gd" },
    ["Git Config"] = { ".gitconfig" },
    ["Gleam"] = { ".gleam" },
    ["GLSL"] = {
        ".glsl",
        ".fp",
        ".frag",
        ".frg",
        ".fs",
        ".fsh",
        ".fshader",
        ".geo",
        ".geom",
        ".glslf",
        ".glslv",
        ".gs",
        ".gshader",
        ".rchit",
        ".rmiss",
        ".shader",
        ".tesc",
        ".tese",
        ".vert",
        ".vrx",
        ".vs",
        ".vsh",
        ".vshader",
    },
    ["Gnuplot"] = { ".gp", ".gnu", ".gnuplot", ".p", ".plot", ".plt" },
    ["Go"] = { ".go" },
    ["GraphQL"] = { ".graphql", ".gql", ".graphqls" },
    ["Groovy"] = { ".groovy", ".grt", ".gtpl", ".gvy" },
    ["Haskell"] = { ".hs", ".hs-boot", ".hsc" },
    ["HCL"] = { ".hcl", ".nomad", ".tf", ".tfvars", ".workflow" },
    ["HTML+EEX"] = { ".eex", ".html.heex", ".html.leex" },
    ["HLSL"] = { ".hlsl", ".cginc", ".fx", ".fxh", ".hlsli" },
    ["HOCON"] = { ".hocon" },
    ["hoon"] = { ".hoon" },
    ["HTML"] = { ".html", ".hta", ".htm", ".html.hl", ".inc", ".xht", ".xhtml" },
    ["HTTP"] = { ".http" },
    ["IDL"] = { ".pro", ".dlm" },
    ["INI"] = { ".ini", ".cfg", ".cnf", ".dof", ".lektorproject", ".prefs", ".pro", ".properties", ".url" },
    ["Janet"] = { ".janet" },
    ["Java"] = { ".java", ".jav", ".jsh" },
    ["JavaScript"] = {
        ".js",
        "._js",
        ".bones",
        ".cjs",
        ".es",
        ".es6",
        ".frag",
        ".gs",
        ".jake",
        ".javascript",
        ".jsb",
        ".jscad",
        ".jsfl",
        ".jslib",
        ".jsm",
        ".jspre",
        ".jss",
        ".jsx",
        ".mjs",
        ".njs",
        ".pac",
        ".sjs",
        ".ssjs",
        ".xsjs",
        ".xsjslib",
    },
    ["jq"] = { ".jq" },
    ["JSON"] = {
        ".json",
        ".4dform",
        ".4dproject",
        ".avsc",
        ".geojson",
        ".gltf",
        ".har",
        ".ice",
        ".json-tmlanguage",
        ".jsonl",
        ".mcmeta",
        ".sarif",
        ".tfstate",
        ".tfstate.backup",
        ".topojson",
        ".webapp",
        ".webmanifest",
        ".yy",
        ".yyp",
    },
    ["JSON5"] = { ".json5" },
    ["JSON with Comments"] = {
        ".jsonc",
        ".code-snippets",
        ".code-workspace",
        ".sublime-build",
        ".sublime-commands",
        ".sublime-completions",
        ".sublime-keymap",
        ".sublime-macro",
        ".sublime-menu",
        ".sublime-mousemap",
        ".sublime-project",
        ".sublime-settings",
        ".sublime-theme",
        ".sublime-workspace",
        ".sublime_metrics",
        ".sublime_session",
    },
    ["Jsonnet"] = { ".jsonnet", ".libsonnet" },
    ["Julia"] = { ".jl" },
    ["Kotlin"] = { ".kt", ".ktm", ".kts" },
    ["Kusto"] = { ".csl", ".kql" },
    ["Linker Script"] = { ".ld", ".lds", ".x" },
    ["Liquid"] = { ".liquid" },
    ["LLVM"] = { ".ll" },
    ["Lua"] = { ".lua", ".fcgi", ".nse", ".p8", ".pd_lua", ".rbxs", ".rockspec", ".wlua" },
    ["Motorola 68K Assembly"] = { ".asm", ".i", ".inc", ".s", ".x68" },
    ["Makefile"] = { ".mak", ".d", ".make", ".makefile", ".mk", ".mkfile" },
    ["MATLAB"] = { ".matlab", ".m" },
    ["MLIR"] = { ".mlir" },
    ["Nim"] = { ".nim", ".nim.cfg", ".nimble", ".nimrod", ".nims" },
    ["Ninja"] = { ".ninja" },
    ["Nix"] = { ".nix" },
    ["Objective-C"] = { ".m", ".h" },
    ["ObjDump"] = { ".objdump" },
    ["OCaml"] = { ".ml", ".eliom", ".eliomi", ".ml4", ".mli", ".mll", ".mly" },
    ["Odin"] = { ".odin" },
    ["Pascal"] = { ".pas", ".dfm", ".dpr", ".inc", ".lpr", ".pascal", ".pp" },
    ["Perl"] = { ".pl", ".al", ".cgi", ".fcgi", ".perl", ".ph", ".plx", ".pm", ".psgi", ".t" },
    ["PHP"] = { ".php", ".aw", ".ctp", ".fcgi", ".inc", ".php3", ".php4", ".php5", ".phps", ".phpt" },
    ["Pod"] = { ".pod" },
    ["Pony"] = { ".pony" },
    ["Prisma"] = { ".prisma" },
    ["Java Properties"] = { ".properties" },
    ["Protocol Buffer"] = { ".proto" },
    ["Pug"] = { ".jade", ".pug" },
    ["Puppet"] = { ".pp" },
    ["PureScript"] = { ".purs" },
    ["Python"] = {
        ".py",
        ".cgi",
        ".fcgi",
        ".gyp",
        ".gypi",
        ".lmi",
        ".py3",
        ".pyde",
        ".pyi",
        ".pyp",
        ".pyt",
        ".pyw",
        ".rpy",
        ".spec",
        ".tac",
        ".wsgi",
        ".xpy",
    },
    ["CodeQL"] = { ".ql", ".qll" },
    ["QML"] = { ".qml", ".qbs" },
    ["R"] = { ".r", ".rd", ".rsx" },
    ["RBS"] = { ".rbs" },
    ["Regular Expression"] = { ".regexp", ".regex" },
    ["RobotFramework"] = { ".robot" },
    ["Roc"] = { ".roc" },
    ["reStructuredText"] = { ".rst", ".rest", ".rest.txt", ".rst.txt" },
    ["Ruby"] = {
        ".rb",
        ".builder",
        ".eye",
        ".fcgi",
        ".gemspec",
        ".god",
        ".jbuilder",
        ".mspec",
        ".pluginspec",
        ".podspec",
        ".prawn",
        ".rabl",
        ".rake",
        ".rbi",
        ".rbuild",
        ".rbw",
        ".rbx",
        ".ru",
        ".ruby",
        ".spec",
        ".thor",
        ".watchr",
    },
    ["Rust"] = { ".rs", ".rs.in" },
    ["Scala"] = { ".scala", ".kojo", ".sbt", ".sc" },
    ["SCSS"] = { ".scss" },
    ["Shell"] = {
        ".sh",
        ".bash",
        ".bats",
        ".cgi",
        ".command",
        ".fcgi",
        ".ksh",
        ".sh.in",
        ".tool",
        ".trigger",
        ".zsh",
        ".zsh-theme",
    }, -- Removed .tmux to map to tmux parser
    ["Slint"] = { ".slint" },
    ["Smali"] = { ".smali" },
    ["Smithy"] = { ".smithy" },
    ["Solidity"] = { ".sol" },
    ["SourcePawn"] = { ".sp", ".inc" },
    ["SPARQL"] = { ".sparql", ".rq" },
    ["SQL"] = { ".sql", ".cql", ".ddl", ".inc", ".mysql", ".prc", ".tab", ".udf", ".viw" },
    ["Squirrel"] = { ".nut" },
    ["Starlark"] = { ".bzl", ".star" },
    ["SuperCollider"] = { ".sc", ".scd" },
    ["Svelte"] = { ".svelte" },
    ["Swift"] = { ".swift" },
    ["Tcl"] = { ".tcl", ".adp", ".sdc", ".tcl.in", ".tm", ".xdc" },
    ["Protocol Buffer Text Format"] = { ".textproto", ".pbt", ".pbtxt" },
    ["Thrift"] = { ".thrift" },
    ["TLA"] = { ".tla" },
    ["TOML"] = { ".toml" },
    ["TSV"] = { ".tsv" },
    ["TSX"] = { ".tsx" },
    ["Turtle"] = { ".ttl" },
    ["Twig"] = { ".twig" },
    ["TypeScript"] = { ".ts", ".cts", ".mts" },
    ["Typst"] = { ".typ" },
    ["V"] = { ".v" },
    ["Vala"] = { ".vala", ".vapi" },
    ["Verilog"] = { ".v", ".veo" },
    ["Vim Script"] = { ".vim", ".vba", ".vimrc", ".vmb" },
    ["Vim Help File"] = { ".txt" },
    ["Vue"] = { ".vue" },
    ["WGSL"] = { ".wgsl" },
    ["WebAssembly Interface Type"] = { ".wit" },
    ["XML"] = {
        ".xml",
        ".adml",
        ".admx",
        ".ant",
        ".axaml",
        ".axml",
        ".builds",
        ".ccproj",
        ".ccxml",
        ".clixml",
        ".cproject",
        ".cscfg",
        ".csdef",
        ".csl",
        ".csproj",
        ".ct",
        ".depproj",
        ".dita",
        ".ditamap",
        ".ditaval",
        ".dll.config",
        ".dotsettings",
        ".filters",
        ".fsproj",
        ".fxml",
        ".glade",
        ".gml",
        ".gmx",
        ".grxml",
        ".gst",
        ".hzp",
        ".iml",
        ".ivy",
        ".jelly",
        ".jsproj",
        ".kml",
        ".launch",
        ".mdpolicy",
        ".mjml",
        ".mm",
        ".mod",
        ".mojo",
        ".mxml",
        ".natvis",
        ".ncl",
        ".ndproj",
        ".nproj",
        ".nuspec",
        ".odd",
        ".osm",
        ".pkgproj",
        ".pluginspec",
        ".proj",
        ".props",
        ".ps1xml",
        ".psc1",
        ".pt",
        ".qhelp",
        ".rdf",
        ".res",
        ".resx",
        ".rs",
        ".rss",
        ".sch",
        ".scxml",
        ".sfproj",
        ".shproj",
        ".srdf",
        ".storyboard",
        ".sublime-snippet",
        ".sw",
        ".targets",
        ".tml",
        ".ts",
        ".tsx",
        ".typ",
        ".ui",
        ".urdf",
        ".ux",
        ".vbproj",
        ".vcxproj",
        ".vsixmanifest",
        ".vssettings",
        ".vstemplate",
        ".vxml",
        ".wixproj",
        ".workflow",
        ".wsdl",
        ".wsf",
        ".wxi",
        ".wxl",
        ".wxs",
        ".x3d",
        ".xacro",
        ".xaml",
        ".xib",
        ".xlf",
        ".xliff",
        ".xmi",
        ".xml.dist",
        ".xmp",
        ".xproj",
        ".xsd",
        ".xspec",
        ".xul",
        ".zcml",
    },
    ["YAML"] = {
        ".yml",
        ".mir",
        ".reek",
        ".rviz",
        ".sublime-syntax",
        ".syntax",
        ".yaml",
        ".yaml-tmlanguage",
        ".yaml.sed",
        ".yml.mysql",
    },
    ["YANG"] = { ".yang" },
    ["Zig"] = { ".zig" },

    -- Extras manually added
    ["HJSON"] = { ".hjson" },
    ["NASM"] = { ".nas", ".nasm" },
    ["Tmux"] = { ".tmux" },
}

local enry_ext_to_langs = {
    -- Taken from go-enry's extensions.go file
    [".4dform"] = { "JSON" },
    [".4dproject"] = { "JSON" },
    [".4th"] = { "Forth" },
    ["._js"] = { "JavaScript" },
    [".a51"] = { "Assembly" },
    [".ada"] = { "Ada" },
    [".adb"] = { "Ada" },
    [".adml"] = { "XML" },
    [".admx"] = { "XML" },
    [".adp"] = { "Tcl" },
    [".ads"] = { "Ada" },
    [".agda"] = { "Agda" },
    [".al"] = { "Perl" },
    [".ant"] = { "XML" },
    [".app"] = { "Erlang" },
    [".app.src"] = { "Erlang" },
    [".asd"] = { "Common Lisp" },
    [".asm"] = { "Assembly", "Motorola 68K Assembly" },
    [".astro"] = { "Astro" },
    [".avsc"] = { "JSON" },
    [".aw"] = { "PHP" },
    [".axaml"] = { "XML" },
    [".axml"] = { "XML" },
    [".bash"] = { "Shell" },
    [".bats"] = { "Shell" },
    [".bb"] = { "BitBake", "Clojure" },
    [".bbappend"] = { "BitBake" },
    [".bbclass"] = { "BitBake" },
    [".bib"] = { "BibTeX" },
    [".bibtex"] = { "BibTeX" },
    [".bicep"] = { "Bicep" },
    [".bicepparam"] = { "Bicep" },
    [".bones"] = { "JavaScript" },
    [".boot"] = { "Clojure" },
    [".builder"] = { "Ruby" },
    [".builds"] = { "XML" },
    [".bzl"] = { "Starlark" },
    [".c"] = { "C" },
    [".c++"] = { "C++" },
    [".cairo"] = { "Cairo" },
    [".cake"] = { "C#" },
    [".capnp"] = { "Cap'n Proto" },
    [".cats"] = { "C" },
    [".cc"] = { "C++" },
    [".ccproj"] = { "XML" },
    [".ccxml"] = { "XML" },
    [".cfg"] = { "INI" },
    [".cgi"] = { "Python", "Perl", "Shell" },
    [".cginc"] = { "HLSL" },
    [".cjs"] = { "JavaScript" },
    [".cl"] = { "Common Lisp" },
    [".cl2"] = { "Clojure" },
    [".clixml"] = { "XML" },
    [".clj"] = { "Clojure" },
    [".cljc"] = { "Clojure" },
    [".cljs"] = { "Clojure" },
    [".cljs.hl"] = { "Clojure" },
    [".cljscm"] = { "Clojure" },
    [".cljx"] = { "Clojure" },
    [".cls"] = { "Apex" },
    [".cmake"] = { "CMake" },
    [".cmake.in"] = { "CMake" },
    [".cnf"] = { "INI" },
    [".code-snippets"] = { "JSON with Comments" },
    [".code-workspace"] = { "JSON with Comments" },
    [".command"] = { "Shell" },
    [".cp"] = { "C++" },
    [".cpp"] = { "C++" },
    [".cppm"] = { "C++" },
    [".cproject"] = { "XML" },
    [".cql"] = { "SQL" },
    [".cs"] = { "C#" },
    [".cs.pp"] = { "C#" },
    [".cscfg"] = { "XML" },
    [".csdef"] = { "XML" },
    [".csl"] = { "Kusto", "XML" },
    [".csproj"] = { "XML" },
    [".css"] = { "CSS" },
    [".csv"] = { "CSV" },
    [".csx"] = { "C#" },
    [".ct"] = { "XML" },
    [".ctp"] = { "PHP" },
    [".cts"] = { "TypeScript" },
    [".cu"] = { "Cuda" },
    [".cue"] = { "CUE" },
    [".cuh"] = { "Cuda" },
    [".cxx"] = { "C++" },
    [".d"] = { "D", "Makefile" },
    [".dart"] = { "Dart" },
    [".ddl"] = { "SQL" },
    [".depproj"] = { "XML" },
    [".dfm"] = { "Pascal" },
    [".dhall"] = { "Dhall" },
    [".di"] = { "D" },
    [".diff"] = { "Diff" },
    [".dita"] = { "XML" },
    [".ditamap"] = { "XML" },
    [".ditaval"] = { "XML" },
    [".dll.config"] = { "XML" },
    [".dlm"] = { "IDL" },
    [".dockerfile"] = { "Dockerfile" },
    [".dof"] = { "INI" },
    [".dotsettings"] = { "XML" },
    [".dpr"] = { "Pascal" },
    [".dsp"] = { "Faust" },
    [".ebnf"] = { "EBNF" },
    [".eex"] = { "HTML+EEX" },
    [".eliom"] = { "OCaml" },
    [".eliomi"] = { "OCaml" },
    [".elm"] = { "Elm" },
    [".elv"] = { "Elvish" },
    [".erl"] = { "Erlang" },
    [".es"] = { "Erlang", "JavaScript" },
    [".es6"] = { "JavaScript" },
    [".escript"] = { "Erlang" },
    [".ex"] = { "Elixir" },
    [".exs"] = { "Elixir" },
    [".eye"] = { "Ruby" },
    [".f"] = { "Forth", "Fortran" },
    [".f77"] = { "Fortran" },
    [".fcgi"] = { "PHP", "Lua", "Ruby", "Python", "Perl", "Shell" },
    [".filters"] = { "XML" },
    [".fish"] = { "fish" },
    [".fnl"] = { "Fennel" },
    [".for"] = { "Forth", "Fortran" },
    [".forth"] = { "Forth" },
    [".fp"] = { "GLSL" },
    [".fpp"] = { "Fortran" },
    [".fr"] = { "Forth" },
    [".frag"] = { "JavaScript", "GLSL" },
    [".frg"] = { "GLSL" },
    [".frt"] = { "Forth" },
    [".fs"] = { "Forth", "GLSL" },
    [".fsh"] = { "GLSL" },
    [".fshader"] = { "GLSL" },
    [".fsproj"] = { "XML" },
    [".fth"] = { "Forth" },
    [".fx"] = { "HLSL" },
    [".fxh"] = { "HLSL" },
    [".fxml"] = { "XML" },
    [".gd"] = { "GDScript" },
    [".gemspec"] = { "Ruby" },
    [".geo"] = { "GLSL" },
    [".geojson"] = { "JSON" },
    [".geom"] = { "GLSL" },
    [".gitconfig"] = { "Git Config" },
    [".glade"] = { "XML" },
    [".gleam"] = { "Gleam" },
    [".glsl"] = { "GLSL" },
    [".glslf"] = { "GLSL" },
    [".glslv"] = { "GLSL" },
    [".gltf"] = { "JSON" },
    [".gml"] = { "XML" },
    [".gmx"] = { "XML" },
    [".gnu"] = { "Gnuplot" },
    [".gnuplot"] = { "Gnuplot" },
    [".go"] = { "Go" },
    [".god"] = { "Ruby" },
    [".gp"] = { "Gnuplot" },
    [".gql"] = { "GraphQL" },
    [".graphql"] = { "GraphQL" },
    [".graphqls"] = { "GraphQL" },
    [".groovy"] = { "Groovy" },
    [".grt"] = { "Groovy" },
    [".grxml"] = { "XML" },
    [".gs"] = { "JavaScript", "GLSL" },
    [".gshader"] = { "GLSL" },
    [".gst"] = { "XML" },
    [".gtpl"] = { "Groovy" },
    [".gvy"] = { "Groovy" },
    [".gyp"] = { "Python" },
    [".gypi"] = { "Python" },
    [".h"] = { "Objective-C", "C", "C++" },
    [".h++"] = { "C++" },
    [".har"] = { "JSON" },
    [".hcl"] = { "HCL" },
    [".hh"] = { "C++" },
    [".hic"] = { "Clojure" },
    [".hlsl"] = { "HLSL" },
    [".hlsli"] = { "HLSL" },
    [".hocon"] = { "HOCON" },
    [".hoon"] = { "hoon" },
    [".hpp"] = { "C++" },
    [".hrl"] = { "Erlang" },
    [".hs"] = { "Haskell" },
    [".hs-boot"] = { "Haskell" },
    [".hsc"] = { "Haskell" },
    [".hta"] = { "HTML" },
    [".htm"] = { "HTML" },
    [".html"] = { "HTML" },
    [".html.heex"] = { "HTML+EEX" },
    [".html.hl"] = { "HTML" },
    [".html.leex"] = { "HTML+EEX" },
    [".http"] = { "HTTP" },
    [".hxx"] = { "C++" },
    [".hzp"] = { "XML" },
    [".i"] = { "Assembly", "Motorola 68K Assembly" },
    [".ice"] = { "JSON" },
    [".idc"] = { "C" },
    [".iml"] = { "XML" },
    [".inc"] = { "Assembly", "PHP", "HTML", "C++", "BitBake", "Pascal", "SQL", "SourcePawn", "Motorola 68K Assembly" },
    [".ini"] = { "INI" },
    [".inl"] = { "C++" },
    [".ino"] = { "C++" },
    [".ipp"] = { "C++" },
    [".ivy"] = { "XML" },
    [".ixx"] = { "C++" },
    [".jade"] = { "Pug" },
    [".jake"] = { "JavaScript" },
    [".janet"] = { "Janet" },
    [".jav"] = { "Java" },
    [".java"] = { "Java" },
    [".javascript"] = { "JavaScript" },
    [".jbuilder"] = { "Ruby" },
    [".jelly"] = { "XML" },
    [".jl"] = { "Julia" },
    [".jq"] = { "jq" },
    [".js"] = { "JavaScript" },
    [".jsb"] = { "JavaScript" },
    [".jscad"] = { "JavaScript" },
    [".jsfl"] = { "JavaScript" },
    [".jsh"] = { "Java" },
    [".jslib"] = { "JavaScript" },
    [".jsm"] = { "JavaScript" },
    [".json"] = { "JSON" },
    [".json-tmlanguage"] = { "JSON" },
    [".json5"] = { "JSON5" },
    [".jsonc"] = { "JSON with Comments" },
    [".jsonl"] = { "JSON" },
    [".jsonnet"] = { "Jsonnet" },
    [".jspre"] = { "JavaScript" },
    [".jsproj"] = { "XML" },
    [".jss"] = { "JavaScript" },
    [".jsx"] = { "JavaScript" },
    [".kml"] = { "XML" },
    [".kojo"] = { "Scala" },
    [".kql"] = { "Kusto" },
    [".ksh"] = { "Shell" },
    [".kt"] = { "Kotlin" },
    [".ktm"] = { "Kotlin" },
    [".kts"] = { "Kotlin" },
    [".l"] = { "Common Lisp" },
    [".launch"] = { "XML" },
    [".ld"] = { "Linker Script" },
    [".lds"] = { "Linker Script" },
    [".lektorproject"] = { "INI" },
    [".libsonnet"] = { "Jsonnet" },
    [".linq"] = { "C#" },
    [".liquid"] = { "Liquid" },
    [".lisp"] = { "Common Lisp" },
    [".ll"] = { "LLVM" },
    [".lmi"] = { "Python" },
    [".lpr"] = { "Pascal" },
    [".lsp"] = { "Common Lisp" },
    [".lua"] = { "Lua" },
    [".m"] = { "Objective-C", "MATLAB" },
    [".mak"] = { "Makefile" },
    [".make"] = { "Makefile" },
    [".makefile"] = { "Makefile" },
    [".matlab"] = { "MATLAB" },
    [".mcmeta"] = { "JSON" },
    [".mdpolicy"] = { "XML" },
    [".mir"] = { "YAML" },
    [".mjml"] = { "XML" },
    [".mjs"] = { "JavaScript" },
    [".mk"] = { "Makefile" },
    [".mkfile"] = { "Makefile" },
    [".ml"] = { "OCaml" },
    [".ml4"] = { "OCaml" },
    [".mli"] = { "OCaml" },
    [".mlir"] = { "MLIR" },
    [".mll"] = { "OCaml" },
    [".mly"] = { "OCaml" },
    [".mm"] = { "XML" },
    [".mod"] = { "XML" },
    [".mojo"] = { "XML" },
    [".mspec"] = { "Ruby" },
    [".mts"] = { "TypeScript" },
    [".mxml"] = { "XML" },
    [".mysql"] = { "SQL" },
    [".nas"] = { "Assembly" },
    [".nasm"] = { "Assembly" },
    [".natvis"] = { "XML" },
    [".ncl"] = { "XML" },
    [".ndproj"] = { "XML" },
    [".nim"] = { "Nim" },
    [".nim.cfg"] = { "Nim" },
    [".nimble"] = { "Nim" },
    [".nimrod"] = { "Nim" },
    [".nims"] = { "Nim" },
    [".ninja"] = { "Ninja" },
    [".nix"] = { "Nix" },
    [".njs"] = { "JavaScript" },
    [".nomad"] = { "HCL" },
    [".nproj"] = { "XML" },
    [".nse"] = { "Lua" },
    [".nuspec"] = { "XML" },
    [".nut"] = { "Squirrel" },
    [".ny"] = { "Common Lisp" },
    [".objdump"] = { "ObjDump" },
    [".odd"] = { "XML" },
    [".odin"] = { "Odin" },
    [".osm"] = { "XML" },
    [".p"] = { "Gnuplot" },
    [".p8"] = { "Lua" },
    [".pac"] = { "JavaScript" },
    [".pas"] = { "Pascal" },
    [".pascal"] = { "Pascal" },
    [".patch"] = { "Diff" },
    [".pbt"] = { "Protocol Buffer Text Format" },
    [".pbtxt"] = { "Protocol Buffer Text Format" },
    [".pd_lua"] = { "Lua" },
    [".perl"] = { "Perl" },
    [".ph"] = { "Perl" },
    [".php"] = { "PHP" },
    [".php3"] = { "PHP" },
    [".php4"] = { "PHP" },
    [".php5"] = { "PHP" },
    [".phps"] = { "PHP" },
    [".phpt"] = { "PHP" },
    [".pkgproj"] = { "XML" },
    [".pl"] = { "Perl" },
    [".plot"] = { "Gnuplot" },
    [".plt"] = { "Gnuplot" },
    [".pluginspec"] = { "Ruby", "XML" },
    [".plx"] = { "Perl" },
    [".pm"] = { "Perl" },
    [".pod"] = { "Pod" },
    [".podsl"] = { "Common Lisp" },
    [".podspec"] = { "Ruby" },
    [".pony"] = { "Pony" },
    [".pp"] = { "Pascal", "Puppet" },
    [".prawn"] = { "Ruby" },
    [".prc"] = { "SQL" },
    [".prefs"] = { "INI" },
    [".prisma"] = { "Prisma" },
    [".pro"] = { "IDL", "INI" },
    [".proj"] = { "XML" },
    [".properties"] = { "INI", "Java Properties" },
    [".props"] = { "XML" },
    [".proto"] = { "Protocol Buffer" },
    [".ps1xml"] = { "XML" },
    [".psc1"] = { "XML" },
    [".psgi"] = { "Perl" },
    [".pt"] = { "XML" },
    [".pug"] = { "Pug" },
    [".purs"] = { "PureScript" },
    [".py"] = { "Python" },
    [".py3"] = { "Python" },
    [".pyde"] = { "Python" },
    [".pyi"] = { "Python" },
    [".pyp"] = { "Python" },
    [".pyt"] = { "Python" },
    [".pyw"] = { "Python" },
    [".qbs"] = { "QML" },
    [".qhelp"] = { "XML" },
    [".ql"] = { "CodeQL" },
    [".qll"] = { "CodeQL" },
    [".qml"] = { "QML" },
    [".r"] = { "R" },
    [".rabl"] = { "Ruby" },
    [".rake"] = { "Ruby" },
    [".rb"] = { "Ruby" },
    [".rbi"] = { "Ruby" },
    [".rbs"] = { "RBS" },
    [".rbuild"] = { "Ruby" },
    [".rbw"] = { "Ruby" },
    [".rbx"] = { "Ruby" },
    [".rbxs"] = { "Lua" },
    [".rchit"] = { "GLSL" },
    [".rd"] = { "R" },
    [".rdf"] = { "XML" },
    [".re"] = { "C++" },
    [".reek"] = { "YAML" },
    [".regex"] = { "Regular Expression" },
    [".regexp"] = { "Regular Expression" },
    [".res"] = { "XML" },
    [".rest"] = { "reStructuredText" },
    [".rest.txt"] = { "reStructuredText" },
    [".resx"] = { "XML" },
    [".rmiss"] = { "GLSL" },
    [".robot"] = { "RobotFramework" },
    [".roc"] = { "Roc" },
    [".rockspec"] = { "Lua" },
    [".rpy"] = { "Python" },
    [".rq"] = { "SPARQL" },
    [".rs"] = { "XML", "Rust" },
    [".rs.in"] = { "Rust" },
    [".rss"] = { "XML" },
    [".rst"] = { "reStructuredText" },
    [".rst.txt"] = { "reStructuredText" },
    [".rsx"] = { "R" },
    [".ru"] = { "Ruby" },
    [".ruby"] = { "Ruby" },
    [".rviz"] = { "YAML" },
    [".s"] = { "Motorola 68K Assembly" },
    [".sarif"] = { "JSON" },
    [".sbt"] = { "Scala" },
    [".sc"] = { "SuperCollider", "Scala" },
    [".scala"] = { "Scala" },
    [".scd"] = { "SuperCollider" },
    [".sch"] = { "XML" },
    [".scss"] = { "SCSS" },
    [".scxml"] = { "XML" },
    [".sdc"] = { "Tcl" },
    [".sexp"] = { "Common Lisp" },
    [".sfproj"] = { "XML" },
    [".sh"] = { "Shell" },
    [".sh.in"] = { "Shell" },
    [".shader"] = { "GLSL" },
    [".shproj"] = { "XML" },
    [".sjs"] = { "JavaScript" },
    [".slint"] = { "Slint" },
    [".smali"] = { "Smali" },
    [".smithy"] = { "Smithy" },
    [".sol"] = { "Solidity" },
    [".sp"] = { "SourcePawn" },
    [".sparql"] = { "SPARQL" },
    [".spec"] = { "Ruby", "Python" },
    [".sql"] = { "SQL" },
    [".srdf"] = { "XML" },
    [".ssjs"] = { "JavaScript" },
    [".star"] = { "Starlark" },
    [".storyboard"] = { "XML" },
    [".sublime-build"] = { "JSON with Comments" },
    [".sublime-commands"] = { "JSON with Comments" },
    [".sublime-completions"] = { "JSON with Comments" },
    [".sublime-keymap"] = { "JSON with Comments" },
    [".sublime-macro"] = { "JSON with Comments" },
    [".sublime-menu"] = { "JSON with Comments" },
    [".sublime-mousemap"] = { "JSON with Comments" },
    [".sublime-project"] = { "JSON with Comments" },
    [".sublime-settings"] = { "JSON with Comments" },
    [".sublime-snippet"] = { "XML" },
    [".sublime-syntax"] = { "YAML" },
    [".sublime-theme"] = { "JSON with Comments" },
    [".sublime-workspace"] = { "JSON with Comments" },
    [".sublime_metrics"] = { "JSON with Comments" },
    [".sublime_session"] = { "JSON with Comments" },
    [".svelte"] = { "Svelte" },
    [".sw"] = { "XML" },
    [".swift"] = { "Swift" },
    [".syntax"] = { "YAML" },
    [".t"] = { "Perl" },
    [".tab"] = { "SQL" },
    [".tac"] = { "Python" },
    [".targets"] = { "XML" },
    [".tcc"] = { "C++" },
    [".tcl"] = { "Tcl" },
    [".tcl.in"] = { "Tcl" },
    [".tesc"] = { "GLSL" },
    [".tese"] = { "GLSL" },
    [".textproto"] = { "Protocol Buffer Text Format" },
    [".tf"] = { "HCL" },
    [".tfstate"] = { "JSON" },
    [".tfstate.backup"] = { "JSON" },
    [".tfvars"] = { "HCL" },
    [".thor"] = { "Ruby" },
    [".thrift"] = { "Thrift" },
    [".tla"] = { "TLA" },
    [".tm"] = { "Tcl" },
    [".tml"] = { "XML" },
    [".tool"] = { "Shell" },
    [".toml"] = { "TOML" },
    [".topojson"] = { "JSON" },
    [".tpp"] = { "C++" },
    [".trigger"] = { "Apex", "Shell" },
    [".ts"] = { "TypeScript", "XML" },
    [".tsv"] = { "TSV" },
    [".tsx"] = { "XML", "TSX" },
    [".ttl"] = { "Turtle" },
    [".twig"] = { "Twig" },
    [".txt"] = { "Vim Help File" },
    [".txx"] = { "C++" },
    [".typ"] = { "XML", "Typst" },
    [".udf"] = { "SQL" },
    [".ui"] = { "XML" },
    [".urdf"] = { "XML" },
    [".url"] = { "INI" },
    [".ux"] = { "XML" },
    [".v"] = { "Verilog", "V" },
    [".vala"] = { "Vala" },
    [".vapi"] = { "Vala" },
    [".vba"] = { "Vim Script" },
    [".vbproj"] = { "XML" },
    [".vcxproj"] = { "XML" },
    [".veo"] = { "Verilog" },
    [".vert"] = { "GLSL" },
    [".vim"] = { "Vim Script" },
    [".vimrc"] = { "Vim Script" },
    [".viw"] = { "SQL" },
    [".vmb"] = { "Vim Script" },
    [".vrx"] = { "GLSL" },
    [".vs"] = { "GLSL" },
    [".vsh"] = { "GLSL" },
    [".vshader"] = { "GLSL" },
    [".vsixmanifest"] = { "XML" },
    [".vssettings"] = { "XML" },
    [".vstemplate"] = { "XML" },
    [".vue"] = { "Vue" },
    [".vxml"] = { "XML" },
    [".watchr"] = { "Ruby" },
    [".webapp"] = { "JSON" },
    [".webmanifest"] = { "JSON" },
    [".wgsl"] = { "WGSL" },
    [".wit"] = { "WebAssembly Interface Type" },
    [".wixproj"] = { "XML" },
    [".wlua"] = { "Lua" },
    [".workflow"] = { "XML", "HCL" },
    [".wsdl"] = { "XML" },
    [".wsf"] = { "XML" },
    [".wsgi"] = { "Python" },
    [".wxi"] = { "XML" },
    [".wxl"] = { "XML" },
    [".wxs"] = { "XML" },
    [".x"] = { "Linker Script" },
    [".x3d"] = { "XML" },
    [".x68"] = { "Motorola 68K Assembly" },
    [".xacro"] = { "XML" },
    [".xaml"] = { "XML" },
    [".xdc"] = { "Tcl" },
    [".xht"] = { "HTML" },
    [".xhtml"] = { "HTML" },
    [".xib"] = { "XML" },
    [".xlf"] = { "XML" },
    [".xliff"] = { "XML" },
    [".xmi"] = { "XML" },
    [".xml"] = { "XML" },
    [".xml.dist"] = { "XML" },
    [".xmp"] = { "XML" },
    [".xproj"] = { "XML" },
    [".xpy"] = { "Python" },
    [".xrl"] = { "Erlang" },
    [".xsd"] = { "XML" },
    [".xsjs"] = { "JavaScript" },
    [".xsjslib"] = { "JavaScript" },
    [".xspec"] = { "XML" },
    [".xul"] = { "XML" },
    [".yaml"] = { "YAML" },
    [".yaml-tmlanguage"] = { "YAML" },
    [".yaml.sed"] = { "YAML" },
    [".yang"] = { "YANG" },
    [".yml"] = { "YAML" },
    [".yml.mysql"] = { "YAML" },
    [".yrl"] = { "Erlang" },
    [".yy"] = { "JSON" },
    [".yyp"] = { "JSON" },
    [".zcml"] = { "XML" },
    [".zig"] = { "Zig" },
    [".zsh"] = { "Shell" },
    [".zsh-theme"] = { "Shell" },

    -- Extra extensions needed to identify some languages enry supports, but
    -- map unambiguously to a language with an available parser
    [".hjson"] = { "HJSON" },
    [".tl"] = { "Teal" },
    [".tmux"] = { "Tmux" },
    [".luau"] = { "Luau" },
}

-- Parsers marked with "--No Enry" correspond to a language which cannot be
-- autoidentified by enry. Some may map with a file extension and thus can be
-- handled if an extension or name is submitted through the JSON endpoint and
-- are noted as such.
-- TODO: Embedded parsers and niche parsers may need to be removed. Some
-- parsers which I could not compile need to be removed
local ts_parsers = {
    "ada",
    "agda",
    "angular", -- No Enry
    "apex",
    "arduino", -- No Enry
    "asm",
    "astro",
    "authzed", -- No Enry
    "bash", -- Mixed with shell. Used for sh, zsh, ksh, and so on
    "bass", -- No Enry
    "beancount", -- No Enry
    "bibtex",
    "bicep",
    "bitbake",
    "blueprint", -- No Enry, Gnome Blueprint
    "bp", -- No Enry, Android Blueprint
    "c",
    "c_sharp",
    "cairo",
    "capnp",
    "chatito", -- No Enry. Weird ai shit
    "clojure",
    "cmake",
    "comment", -- Stupid. Should delete
    "commonlisp",
    "cooklang", -- No Enry
    "corn", -- No Enry
    "cpon",
    "cpp",
    "css",
    "csv",
    "cuda",
    "cue",
    "d",
    "dart",
    "devicetree", -- No Enry
    "dhall",
    "diff",
    "disassembly", -- No Enry
    "djot", -- No Enry
    "dockerfile",
    "dot",
    "doxygen", -- No Enry
    "dtd", -- No Enry
    "earthfile", -- No Enry
    "ebnf",
    "eds", -- No Enry
    "eex", -- No Enry
    "elixir",
    "elm",
    "elsa", -- No Enry
    "elvish",
    "erlang",
    "facility", -- No Enry
    "faust",
    "fennel",
    "fidl", -- No Enry
    "firrtl", -- No Enry
    "fish",
    "foam", -- No Enry
    "forth",
    "fortran",
    "fsh", -- No Enry
    "func", -- No Enry
    "fusion", -- No Enry
    "gdscript",
    "gdshader", -- No Enry
    "git_config",
    "git_rebase", -- No Enry
    "gitattributes", -- No Enry
    "gitcommit", -- No Enry
    "gitignore",
    "gleam",
    "glsl",
    "gnuplot",
    "go",
    "gomod", -- No Enry
    "gosum", -- No Enry
    "gotmpl", -- No Enry
    "gowork", -- No Enry
    "gpg", -- No Enry
    "graphql",
    "groovy",
    "gstlaunch", -- No Enry
    "hare", -- No Enry
    "haskell",
    "haskell_persistent", -- No Enry
    "hcl",
    "heex",
    "helm", -- No Enry
    "hjson", -- No Enry. Can be mapped by extension
    "hlsl",
    "hlsplaylist", -- No Enry
    "hocon",
    "hoon",
    "html",
    "htmldjango", -- No Enry
    "http",
    "hurl", -- No Enry
    "hyprlang", -- No Enry
    "idl",
    "ini",
    "inko", -- No Enry
    "ispc", -- No Enry
    "janet_simple",
    "java",
    "javascript",
    "jq",
    "jsdoc", -- No Enry
    "json",
    "json5",
    "jsonc",
    "jsonnet",
    "julia",
    "just", -- No Enry
    "kconfig", -- No Enry
    "kdl", -- No Enry
    "kotlin",
    "koto", -- No Enry
    "kusto",
    "lalrpop", -- No Enry
    "latex",
    "ledger", -- No Enry
    "leo", -- No Enry
    "linkerscript",
    "liquid",
    "liquidsoap", -- No Enry
    "llvm",
    "lua",
    "luadoc", -- No Enry
    "luau", -- No Enry. Mapped to extension
    "m68k",
    "make",
    "matlab",
    "menhir", -- No Enry
    "meson", -- No Enry
    "mlir",
    "muttrc", -- No Enry
    "nasm", -- No Enry. May need later exception based on extension
    "nim",
    "nim_format_string", -- No Enry. Embedded
    "ninja",
    "nix",
    "norg", -- No Enry
    "nqc", -- No Enry
    "objc",
    "objdump",
    "ocaml",
    "ocaml_interface", -- No Enry. Embedded?
    "ocamllex", -- No Enry. Embedded?
    "odin",
    "pascal",
    "passwd", -- No Enry
    "pem", -- No Enry
    "perl",
    "php",
    "php_only", -- No Enry. Embedded?
    "phpdoc", -- No Enry.
    "pioasm", -- No Enry.
    "po", -- No Enry
    "pod",
    "pony",
    "printf", -- No Enry. Embedded?
    "prisma",
    "promql", -- No Enry.
    "properties", -- Java Properties
    "proto", -- Protocol Buffer
    "prql", -- No Enry
    "psv", -- No Enry
    "pug",
    "puppet",
    "purescript",
    "PyPA manifest", -- No Enry
    "python",
    "ql",
    "qmldir", -- No Enry
    "qmljs",
    "r",
    "ralph", -- No Enry
    "rasi",
    "rbs", -- No Enry
    "re2c",
    "readline", -- No Enry.
    "regex",
    "rego",
    "rnoweb", -- No Enry
    "robot",
    "roc",
    "ron", -- No Enry
    "rst",
    "ruby",
    "rust",
    "scala",
    "scfg", -- I don't even know what this is from the parser repository
    "scss",
    "slang", -- No Enry
    "slint",
    "smali",
    "smithy",
    "solidity",
    "soql", -- No Enry
    "sosl", -- No Enry
    "sourcepawn",
    "sparql",
    "sql",
    "squirrel",
    "ssh_config", -- No Enry
    "starlark",
    "strace", -- No Enry
    "styled", -- No Enry
    "supercollider",
    "surface", -- No Enry
    "svelte",
    "swift",
    "sxhkdrc", -- No Enry
    "systemtap", -- No Enry
    "t32", -- No Enry
    "tablegen", -- No Enry
    "tact", -- No Enry
    "tcl",
    "teal", -- No Enry. Mapped to extension
    "templ", -- No Enry
    "terraform", -- For hashicorp configuration language? Seems unrelated to terraform templates in Enry
    "textproto",
    "thrift",
    "tiger", -- No Enry
    "tlaplus",
    "tmux", -- Conflated with shell by enry. Can still be identified by filename
    "todotxt", -- No Enry
    "toml",
    "tsv",
    "tsx",
    "turtle",
    "twig",
    "typescript",
    "typespec", -- No Enry
    "typoscript", -- No Enry
    "typst",
    "udev", -- No Enry
    "ungrammar", -- No Enry
    "unison",
    "usd",
    "uxntal", -- No Enry
    "v",
    "vala",
    "vento", -- No Enry
    "verilog",
    "vhs",
    "vim",
    "vimdoc",
    "vue",
    "wgsl",
    "wgsl_bevy", -- No Enry
    "wing", -- No Enry
    "wit",
    "xcompose", -- No Enry
    "xml",
    "yaml",
    "yang",
    "yuck", -- No Enry
    "zathurarc", -- No Enry
    "zig",
}

local ts_to_enry_map = {
    ["asm"] = "Assembly",
    ["bash"] = "Shell", -- No sh specific parser available. Hope bash is good enough
    ["bibtex"] = "BibTeX",
    ["bitbake"] = "BitBake",
    ["c_sharp"] = "C#",
    ["capnp"] = "Cap'n Proto",
    ["cmake"] = "CMake",
    ["commonlisp"] = "Common Lisp",
    ["cpp"] = "C++",
    ["css"] = "CSS",
    ["csv"] = "CSV",
    ["cue"] = "CUE",
    ["ebnf"] = "EBNF",
    ["fish"] = "fish",
    ["gdscript"] = "GDScript",
    ["git_config"] = "Git Config",
    ["gitignore"] = "Ignore File",
    ["glsl"] = "GLSL",
    ["graphql"] = "GraphQL",
    ["hcl"] = "HCL",
    ["heex"] = "HTML+EEX",
    ["hjson"] = "HJSON",
    ["hlsl"] = "HLSL",
    ["hocon"] = "HOCON",
    ["hoon"] = "hoon",
    ["html"] = "HTML",
    ["http"] = "HTTP",
    ["idl"] = "IDL",
    ["ini"] = "INI",
    ["janet_simple"] = "Janet",
    ["javascript"] = "JavaScript",
    ["jq"] = "jq",
    ["json"] = "JSON",
    ["json5"] = "JSON5",
    ["jsonc"] = "JSON with Comments",
    ["latex"] = "TEX",
    ["linkerscript"] = "Linker Script",
    ["llvm"] = "LLVM",
    ["m68k"] = "Motorola 68K Assembly",
    ["make"] = "Makefile",
    ["matlab"] = "MATLAB",
    ["mlir"] = "MLIR",
    ["nasm"] = "NASM",
    ["objc"] = "Objective-C",
    ["objdump"] = "ObjDump",
    ["ocaml"] = "OCaml",
    ["php"] = "PHP",
    ["properties"] = "Java Properties",
    ["proto"] = "Protocol Buffer",
    ["purescript"] = "PureScript",
    ["ql"] = "CodeQL",
    ["qmljs"] = "QML",
    ["rbs"] = "RBS",
    ["regex"] = "Regular Expression",
    ["rego"] = "Open Policy Expression",
    ["robot"] = "RobotFramework",
    ["rst"] = "reStructuredText",
    ["scss"] = "SCSS",
    ["sourcepawn"] = "SourcePawn",
    ["sparql"] = "SPARQL",
    ["sql"] = "SQL",
    ["supercollider"] = "SuperCollider",
    ["textproto"] = "Protocol Buffer Text Format",
    ["tlaplus"] = "TLA",
    ["toml"] = "TOML",
    ["tsv"] = "TSV",
    ["tsx"] = "TSX",
    ["typescript"] = "TypeScript",
    ["vim"] = "Vim Script",
    ["vimdoc"] = "Vim Help File",
    ["wgsl"] = "WGSL",
    ["wit"] = "WebAssembly Interface Type",
    ["xml"] = "XML",
    ["yaml"] = "YAML",
    ["yang"] = "YANG",
}

local enry_to_ts_map = {}

local allowed_enry_langs = {}

function M.init()
    for key, value in pairs(ts_to_enry_map) do
        enry_to_ts_map[value] = key
    end

    local i = 1
    for key, _ in pairs(enry_lang_to_exts) do
        allowed_enry_langs[i] = key
        i = i + 1
    end
end

--- @param parser string
--- @return string
function M.ts_to_enry(parser)
    local ret = ts_to_enry_map[parser]

    if ret then
        return ret
    end

    ret = parser:gsub("_", " ")
    return ret:sub(1, 1):upper() .. ret:sub(2)
end

--- @param lang string
--- @return string
function M.enry_to_ts(lang)
    local ret = enry_to_ts_map[lang]
    if ret then
        return ret
    end

    return lang:gsub(" ", "_"):lower()
end

--- @return string[]
function M.allowed_langs() return allowed_enry_langs end

--- @return string[]
function M.allowed_parsers() return ts_parsers end

--- @param ext string
--- @return string[]|nil, boolean
function M.langs_from_ext(ext)
    local _ext = ext
    if not ext:sub(1, 1) == "." then
        _ext = ext .. "."
    end

    local langs = enry_ext_to_langs[_ext]

    return langs, langs and #langs == 1
end

--- @param lang string
--- @return string[]|nil, boolean
function M.exts_from_lang(lang)
    local exts = enry_lang_to_exts[lang]
    return exts, exts and #exts == 1
end

--- Takes a given language and attempts to resolve it to an Enry language
--- @param lang string
--- @return string|nil
function M.resolve_lang(lang)
    if not lang then
        return nil
    end

    -- The language is already valid
    if enry_lang_to_exts[lang] then
        return lang
    end

    -- The language is a valid parser
    local ts_lang = M.ts_to_enry(lang:lower():gsub(" ", ""))
    if enry_lang_to_exts[ts_lang] then
        return ts_lang
    end

    -- Something like json, which should be JSON
    local caps_lang = lang:upper()
    local caps_ret = enry_lang_to_exts[caps_lang]
    if caps_ret then
        return caps_lang
    end

    return nil
end

return M
